version: 0.0
windows: linux
files:
  - source: /
    destination: /var/www/html/ECommerceNET
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
